name: Build EXE
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Install PyInstaller
        run: pip install pyinstaller
      - name: Build EXE
        run: |
          pyinstaller `
            --onefile `
            --windowed `
            --clean `
            --noconfirm `
            --hidden-import=pandas `
            --hidden-import=numpy `
            --hidden-import=PyQt5.QtCore `
            --add-data="data/*;data" `
            --add-data="images/*;images" `
            main.py
      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: app-exe
          path: dist/main.exe