name: Build EXE
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install keyboard pyperclip pyinstaller
      - name: Build EXE
        run: |
          mkdir hooks
          echo 'from PyInstaller.utils.hooks import collect_data_files' > hooks/hook-keyboard.py
          echo 'datas = collect_data_files("keyboard")' >> hooks/hook-keyboard.py
          
          pyinstaller `
            --onefile `
            --windowed `
            --clean `
            --noconfirm `
            --additional-hooks-dir=hooks `
            --hidden-import=keyboard `
            --hidden-import=pyperclip `
            main.py

      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: keyboard-hotkey-app
          path: dist/main.exe